<?php

namespace classes;

class AdminClass extends UserClass
{

    /**
     * constructor of class setting property of the class
     */
    public function __construct()
    {
        parent::__construct();
    }

    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }


    /**
     * list all users of type admins
     *
     * @param $type
     * @return array
     */
    public function listAll($type = 'admin')
    {
        return parent::listAll($type); // TODO: Change the autogenerated stub
    }


}